<?php
include('_sys_header.php');
$menu_aktif="akta_cerai";
?>
<div class="loading" id="loader">Loading&#8230;</div>
<!-- Header -->
<div class="w3-top w3-row w3-card-2 w3-padding w3-center w3-white">
    <div class="w3-col" style="width:30px">
        <a href="#" onclick="goBack()" class="headerButton goBack">
            <img src="assets/images/arrow_back-black-24dp.svg" class="w3-left w3-circle w3-margin-right" style="width:30px">
        </a>
    </div>
    <div class="w3-rest w3-cell-middle"><span style="font-size: 18px">KEBIJAKAN DAN PRIVASI</span></div>
</div> 
<!-- Header -->
<br>
<br>
<br>
<!-- Isi -->
<div class="w3-row">
    <div class="w3-container" id="informasi_perkara_inputan"> 
        <p><strong>Kebijakan Privasi</strong></p>
<p>Tanggal efektif : 19 Oktober 2020 Pengadilan Agama Semarang (&ldquo;kami&rdquo;) mengoperasikan SIKOMPAC (Sistem Informasi dan Komputerisasi Pengadilan Agama Semarang) untuk aplikasi mobile berbasis Android (selanjutnya disebut sebagai &ldquo;Layanan&rdquo;). Halaman ini memberi tahu Anda tentang kebijakan kami mengenai pengumpulan, penggunaan, dan pengungkapan data pribadi saat Anda menggunakan Layanan kami dan pilihan yang telah Anda kaitkan dengan data itu. Kami menggunakan data Anda untuk menyediakan dan meningkatkan Layanan. Dengan menggunakan Layanan, Anda menyetujui pengumpulan dan penggunaan informasi sesuai dengan kebijakan ini. Kecuali ditentukan lain dalam Kebijakan Privasi ini, istilah yang digunakan dalam Kebijakan Privasi ini memiliki arti yang sama seperti dalam Syarat dan Ketentuan kami.</p>
<p><strong>Definisi</strong><br /><strong>Layanan</strong><br />Layanan adalah SIKOMPAC (Sistem Informasi dan Komputerisasi Pengadilan Agama Semarang) untuk aplikasi mobile berbasis Android yang dioperasikan oleh Pengadilan Agama Semarang</p>
<p><strong>Data Pribadi</strong><br />Data Pribadi adalah data tentang individu yang hidup yang dapat diidentifikasi dari data tersebut (atau dari mereka dan informasi lain baik yang kita miliki atau yang kemungkinan akan menjadi milik kita).</p>
<p><strong>Data Penggunaan</strong><br />Data Penggunaan adalah data yang dikumpulkan secara otomatis baik yang dihasilkan oleh penggunaan Layanan atau dari infrastruktur Layanan itu sendiri (misalnya, durasi kunjungan halaman).</p>
<p><strong>Cookie</strong><br />Cookie adalah file kecil yang disimpan di perangkat Anda (komputer atau perangkat seluler).</p>
<p><strong>Pengumpulan dan Penggunaan Informasi</strong><br />Kami mengumpulkan beberapa jenis informasi yang berbeda untuk berbagai keperluan untuk menyediakan dan meningkatkan Layanan kami kepada Anda.</p>
<p><strong>Jenis Data yang Dikumpulkan</strong><br />Data Pribadi Saat menggunakan Layanan kami, kami dapat meminta Anda untuk memberikan kami informasi pengenal pribadi tertentu yang dapat digunakan untuk menghubungi atau mengidentifikasi Anda (&ldquo;Data Pribadi&rdquo;). Informasi yang dapat diidentifikasi secara pribadi dapat mencakup, tetapi tidak terbatas pada:<br />Nama dan&nbsp;Nomor telepon</p>
<p><strong>Cookie dan Data Penggunaan</strong><br />Data Penggunaan Saat Anda mengakses Layanan dengan perangkat seluler, kami dapat mengumpulkan informasi tertentu secara otomatis, termasuk, tetapi tidak terbatas pada, jenis perangkat seluler yang Anda gunakan, ID unik perangkat seluler Anda, alamat IP perangkat seluler Anda, sistem operasi seluler Anda , jenis browser Internet seluler yang Anda gunakan, pengidentifikasi perangkat unik, dan data diagnostik lainnya (&ldquo;Data Penggunaan&rdquo;). Data Tracking &amp; Cookie Kami menggunakan cookie dan teknologi pelacakan serupa untuk melacak aktivitas di Layanan kami dan kami menyimpan informasi tertentu. Cookie adalah file dengan sedikit data yang dapat menyertakan pengidentifikasi unik anonim. Cookie dikirim ke browser Anda dari situs web dan disimpan di perangkat Anda. Teknologi pelacakan lain juga digunakan seperti suar, tag, dan skrip untuk mengumpulkan dan melacak informasi dan untuk meningkatkan dan menganalisis Layanan kami. Anda dapat menginstruksikan browser Anda untuk menolak semua cookie atau untuk menunjukkan kapan cookie dikirim. Namun, jika Anda tidak menerima cookie, Anda mungkin tidak dapat menggunakan sebagian Layanan kami. Contoh Cookie yang kami gunakan:<br />Cookie Sesi. Kami menggunakan Cookie Sesi untuk mengoperasikan layanan kami.<br />Cookie Preferensi. Kami menggunakan Cookie Preferensi untuk mengingat preferensi Anda dan berbagai pengaturan.<br />Cookie Keamanan. Kami menggunakan Cookie Keamanan untuk tujuan keamanan.</p>
<p><br /><strong>Penggunaan Data</strong><br />Pengadilan Agama Semarang menggunakan data yang dikumpulkan untuk berbagai keperluan:<br />Untuk menyediakan dan memelihara Layanan kami<br />Untuk memberitahukan Anda tentang perubahan didalam pelayanan kami<br />Untuk memungkinkan Anda berpartisipasi dalam fitur interaktif Layanan kami ketika Anda memilih untuk melakukannya<br />Untuk memberikan dukungan pelanggan<br />Untuk mengumpulkan analisis atau informasi berharga sehingga kami dapat meningkatkan Layanan kami<br />Untuk memantau penggunaan Layanan kami<br />Untuk mendeteksi, mencegah dan mengatasi masalah teknis</p>
<p><br /><strong>Transfer Data</strong><br />Informasi Anda, termasuk Data Pribadi, dapat ditransfer ke &ndash; dan dipelihara di &ndash; komputer yang berlokasi di luar negara bagian, provinsi, negara atau yurisdiksi pemerintah lainnya di mana undang-undang perlindungan data mungkin berbeda dari yang ada di yurisdiksi Anda. Jika Anda berada di luar Indonesia dan memilih untuk memberikan informasi kepada kami, harap perhatikan bahwa kami mentransfer data, termasuk Data Pribadi, ke Indonesia dan memprosesnya di sana. Persetujuan Anda untuk Kebijakan Privasi ini diikuti dengan pengiriman informasi tersebut merupakan persetujuan Anda untuk transfer tersebut. Pengadilan Agama Semarang akan mengambil semua langkah yang wajar diperlukan untuk memastikan bahwa data Anda diperlakukan dengan aman dan sesuai dengan Kebijakan Privasi ini dan tidak ada transfer Data Pribadi Anda yang akan terjadi pada suatu organisasi atau negara kecuali ada kontrol yang memadai termasuk keamanan data Anda dan informasi pribadi lainnya.</p>
<p><strong>Keterbukaan Data</strong><br />Pengungkapan untuk Penegakan Hukum Dalam keadaan tertentu, Pengadilan Agama Semarang mungkin diharuskan untuk mengungkapkan Data Pribadi Anda jika diharuskan untuk melakukannya oleh hukum atau sebagai tanggapan atas permintaan yang sah oleh otoritas publik (misalnya pengadilan atau lembaga pemerintah). Persyaratan Resmi Pengadilan Agama Semarang dapat mengungkapkan Data Pribadi Anda dengan itikad baik bahwa tindakan tersebut diperlukan untuk:<br />Untuk mematuhi kewajiban hukum<br />Untuk melindungi dan mempertahankan hak atau properti Pengadilan Agama Semarang<br />Untuk mencegah atau menyelidiki kesalahan yang mungkin terjadi sehubungan dengan Layanan<br />Untuk melindungi keamanan pribadi pengguna Layanan atau publik<br />Untuk melindungi terhadap tanggung jawab hukum</p>
<p><br /><strong>Keamanan Data</strong><br />Keamanan data Anda penting bagi kami tetapi ingat bahwa tidak ada metode transmisi melalui Internet atau metode penyimpanan elektronik yang 100% aman. Meskipun kami berusaha untuk menggunakan cara yang dapat diterima secara komersial untuk melindungi Data Pribadi Anda, kami tidak dapat menjamin keamanan mutlaknya.</p>
<p>Penyedia Jasa<br />Kami dapat mempekerjakan perusahaan pihak ketiga dan individu untuk memfasilitasi Layanan kami (&ldquo;Penyedia Layanan&rdquo;), memberikan Layanan atas nama kami, melakukan layanan terkait Layanan atau membantu kami dalam menganalisis bagaimana Layanan kami digunakan. Pihak ketiga ini memiliki akses ke Data Pribadi Anda hanya untuk melakukan tugas-tugas ini atas nama kami dan wajib untuk tidak mengungkapkan atau menggunakannya untuk tujuan lain apa pun.</p>
<p><strong>Analisis</strong><br />Kami dapat menggunakan Penyedia Layanan pihak ketiga untuk memantau dan menganalisis penggunaan Layanan kami.<br />Google Analytics<br />Google Analytics adalah layanan analisis web yang ditawarkan oleh Google yang melacak dan melaporkan lalu lintas situs web. Google menggunakan data yang dikumpulkan untuk melacak dan memantau penggunaan Layanan kami. Data ini dibagikan dengan layanan Google lainnya. Google dapat menggunakan data yang dikumpulkan untuk mengontekstualisasikan dan mempersonalisasikan iklan dari jaringan iklannya sendiri. Anda dapat memilih keluar dari fitur Google Analytics tertentu melalui pengaturan perangkat seluler Anda, seperti pengaturan iklan perangkat Anda atau dengan mengikuti instruksi yang diberikan oleh Google dalam Kebijakan Privasi mereka: https://policies.google.com/privacy?hl=id Untuk informasi lebih lanjut tentang praktik privasi Google, silakan kunjungi halaman web Google Privacy &amp; Terms: https://policies.google.com/privacy?hl=id</p>
<p><strong>Privasi Anak</strong><br />Layanan kami tidak membahas siapa pun yang berusia di bawah 18 tahun (&ldquo;Anak-anak&rdquo;). Kami tidak secara sadar mengumpulkan informasi yang dapat diidentifikasi secara pribadi dari siapa pun yang berusia di bawah 18 tahun. Jika Anda adalah orang tua atau wali dan Anda mengetahui bahwa Anak Anda telah memberikan kepada kami Data Pribadi, silakan hubungi kami. Jika kami mengetahui bahwa kami telah mengumpulkan Data Pribadi dari anak-anak tanpa verifikasi izin orang tua, kami mengambil langkah-langkah untuk menghapus informasi itu dari server kami.</p>
<p><strong>Perubahan pada Kebijakan Privasi Ini</strong><br />Kami dapat memperbarui Kebijakan Privasi kami dari waktu ke waktu. Kami akan memberi tahu Anda tentang segala perubahan dengan memposting Kebijakan Privasi baru di halaman ini. Kami akan memberi tahu Anda melalui email dan / atau pemberitahuan penting pada Layanan kami, sebelum perubahan menjadi efektif dan memperbarui &ldquo;tanggal efektif&rdquo; di bagian atas Kebijakan Privasi ini. Anda disarankan untuk meninjau Kebijakan Privasi ini secara berkala untuk setiap perubahan. Perubahan pada Kebijakan Privasi ini efektif ketika diposkan pada halaman ini.</p>
<p><strong>Kontak Kami</strong><br />Jika Anda memiliki pertanyaan tentang Kebijakan Privasi ini, silakan hubungi kami:<br />Dengan nomor telepon: +62282533455<br />WhatApp : +6281344250233<br />Melalui alamat email : pacilacap.401086@gmail.com</p>
    </div>
</div>
    
    

    <!-- * App Capsule -->

     
<?php include('_sys_footer.php');?>